TARGET = Field_Template_April
CPP_SOURCES = Field_Template_April.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
