TARGET = x0x_drum_machine
CPP_SOURCES = x0x_drum_machine.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
