TARGET      = Field_AdditiveSynth_2
CPP_SOURCES = Field_AdditiveSynth_2.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

USE_DAISYSP_LGPL = 1

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
