# Project Name
TARGET = GeneticSequencer

# Sources
CPP_SOURCES = GeneticSequencer.cpp genetic_algorithm.cpp sequencer.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Core location
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core

# Include system makefile
include $(SYSTEM_FILES_DIR)/Makefile
