# Project Name
TARGET = DrumMachine

# Sources
CPP_SOURCES = DrumMachine.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# No LGPL modules used (AnalogBassDrum, SyntheticSnareDrum, HiHat are MIT)

# Core location, and target
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
