# Project Name
TARGET = multi_fx_synth_pod

# Sources
CPP_SOURCES = multi_fx_synth_pod.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Uncomment for LGPL modules (StringVoice, ModalVoice, ReverbSc, MoogLadder, Compressor)
USE_DAISYSP_LGPL = 1

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
