TARGET = tripple_osc_subtractive
CPP_SOURCES = tripple_osc_subtractive.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
