# Project Name
TARGET = Seed_MIDI_Grainlet

# Sources
CPP_SOURCES = Seed_MIDI_Grainlet.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

# Core location, and generic Makefile
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
