TARGET = Field_GlitchDrumPerformer
CPP_SOURCES = Field_GlitchDrumPerformer.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
