# Project Name
TARGET = MultiDelay

# Sources
CPP_SOURCES = MultiDelay.cpp ../../DaisyHost/src/apps/MultiDelayCore.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP
C_INCLUDES += -I../../DaisyHost/include
OPT = -Os

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
