#!/usr/bin/env python3
"""Validate original tutorial data and generate the firmware table. --check never writes."""
import argparse,json,math,re,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def generate(data):
    entries=data.get("presets",[])
    if data.get("schema")!=1 or len(entries)!=8: raise ValueError("expected schema 1 and 8 presets")
    result=['// Generated by tools/generate_presets.py; edit presets/tutorials.json instead.',
            '// clang-format off','#pragma once','#include "src/app/Types.h"','namespace hydrapulse {',
            'inline const std::array<Preset,kPresets> kTutorialPresets{{']
    def number(x):
        if not isinstance(x,(int,float)) or isinstance(x,bool) or not math.isfinite(x): raise ValueError("nonfinite/non-numeric")
        return f'{float(x):.7f}f'
    for i,p in enumerate(entries):
        if p["id"]!=i or not re.fullmatch(r"[A-Za-z0-9 ]{1,20}",p["name"]): raise ValueError("bad preset identity")
        if not 40<=p["bpm"]<=240 or not 0<=p["swing"]<=1 or not 0<=p["drive"]<=1: raise ValueError("global range")
        if len(p["voices"])!=4: raise ValueError("voice count")
        voices=[]
        for v in p["voices"]:
            vals=[v[k] for k in ("tune","decay","character","level")]
            if any(not isinstance(x,(int,float)) or not math.isfinite(x) or not 0<=x<=1 for x in vals): raise ValueError("voice range")
            voices.append('{'+','.join(number(x) for x in vals)+'}')
        masks=[]
        for key in ("notes","accents"):
            banks=p[key]
            if len(banks)!=3 or any(len(b)!=4 for b in banks): raise ValueError("bank shape")
            if any(type(m) is not int or not 0<=m<=65535 for b in banks for m in b): raise ValueError("mask range")
            masks.append('{{'+','.join('{{'+','.join(f'0x{m:04x}u' for m in b)+'}}' for b in banks)+'}}')
        for b in range(3):
            for t in range(4):
                if p["accents"][b][t] & ~p["notes"][b][t]: raise ValueError("accent without note")
        result.append('    {"'+p["name"]+'",'+','.join(number(p[k]) for k in ("bpm","swing","drive"))+
                      ',{{'+','.join(voices)+'}},'+','.join(masks)+'},')
    result+=['}};','} // namespace hydrapulse','// clang-format on','']
    return '\n'.join(result)
def main():
    ap=argparse.ArgumentParser();ap.add_argument("--check",action="store_true");args=ap.parse_args()
    try:
        text=generate(json.loads((ROOT/'presets/tutorials.json').read_text()))
        output=ROOT/'src/app/Presets.generated.h'
        if args.check:
            if not output.exists() or output.read_text()!=text: raise ValueError("generated presets are stale")
        else: output.write_text(text)
    except (ValueError,KeyError,TypeError,OSError) as exc: print(exc,file=sys.stderr);return 1
    print("presets: PASS");return 0
if __name__=="__main__":sys.exit(main())
