TARGET = Field_WavetableDroneLab
CPP_SOURCES = Field_WavetableDroneLab.cpp

# Library Locations (from MyProjects/_projects/ProjectName/)
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

USE_DAISYSP_LGPL = 1

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

