# Generative Ambient Garden - Daisy Field
TARGET = Field_AmbientGarden

USE_DAISYSP_LGPL = 1

CPP_SOURCES = Field_AmbientGarden.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
