# Project Name
TARGET = fm_synth_field_simple

# Sources
CPP_SOURCES = fm_synth_field_simple.cpp

# Library Locations
LIBDAISY_DIR = ../../../../libDaisy
DAISYSP_DIR = ../../../../DaisySP

# NOT using LGPL modules
# USE_DAISYSP_LGPL = 1

# Core location, and generic Makefile
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
