# Project Name
TARGET = Pomodoro_Pod

# Sources
CPP_SOURCES = Pomodoro_Pod.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Core location
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core

# Include system makefile
include $(SYSTEM_FILES_DIR)/Makefile
