TARGET = Field_AnalogDrumCore
CPP_SOURCES = Field_AnalogDrumCore.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
