# Project Name
TARGET = stringvoice_overdrive_reverb

# Sources
CPP_SOURCES = stringvoice_overdrive_reverb.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Enable LGPL modules for StringVoice and ReverbSc (physical modeling + reverb)
USE_DAISYSP_LGPL = 1

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
