# Project Name
TARGET = Pod_MultiFX_Chain

# Sources
CPP_SOURCES = Pod_MultiFX_Chain.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Enable LGPL modules (ReverbSc)
USE_DAISYSP_LGPL = 1

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
