# Project Name
TARGET = pod_fuzz_distortion

# LGPL modules (ReverbSc)
USE_DAISYSP_LGPL = 1

# Sources
CPP_SOURCES = pod_fuzz_distortion.cpp modal_voice.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR = ../../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
