# Project Name
TARGET = SubharmoniqField

# Sources
CPP_SOURCES = SubharmoniqField.cpp ../../DaisyHost/src/DaisySubharmoniqCore.cpp ../../DaisyHost/src/apps/SubharmoniqCore.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP
C_INCLUDES += -I../../DaisyHost/include
OPT = -Os

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
