TARGET = Pod_OLED_EuclideanDrums
CPP_SOURCES = Pod_OLED_EuclideanDrums.cpp
C_INCLUDES += -I$(LIBDAISY_DIR)/src/ -I$(LIBDAISY_DIR)/src/dev/

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
