# Project Name
TARGET = Field_MI_Rings

# Sources
CPP_SOURCES = Field_MI_Rings.cpp

# Library Locations
LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
