/**
 * apiReferenceInjector.ts — DaisySP API Reference Comment Block Generator
 *
 * Tier 1 of the De-Hallucination system. Given a list of DaisySP class names,
 * generates a structured C++ comment block containing verified method signatures.
 *
 * Prepend this block to any generated .cpp file to ground subsequent LLM
 * code generation against the real DaisySP API.
 *
 * Usage:
 *   const header = buildApiReferenceHeader(['MoogLadder', 'Adsr', 'Oscillator']);
 *   const fullCpp = header + existingCppOutput;
 */

import { DAISY_API_INDEX, lookupClass, DaisyAPIRef } from './daisyApiIndex';

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Builds a C++ comment block with API references for a given set of raw class names.
 *
 * @param rawClassNames  Array of DaisySP class names. May include the 'daisysp::' namespace
 *                       prefix or not — both formats are handled. Duplicates are collapsed.
 * @returns              Formatted multi-line comment string ending with '\n\n',
 *                       or empty string if no recognized DaisySP classes are found.
 *
 * @example
 *   buildApiReferenceHeader(['daisysp::MoogLadder', 'Adsr'])
 *   // Returns comment block with [Adsr] and [MoogLadder] sections (sorted)
 *
 *   buildApiReferenceHeader(['audio_in', 'audio_out'])
 *   // Returns '' — I/O-only patch, no DaisySP DSP classes
 */
export function buildApiReferenceHeader(rawClassNames: string[]): string {
    const refs = collectUniqueRefs(rawClassNames);
    if (refs.length === 0) return '';

    const lines: string[] = [
        '// ============================================================',
        '// DAISYSP API REFERENCE — auto-generated by DVPE',
        '// Grounding reference: verified signatures from DaisySP source.',
        '// Use ONLY methods listed here. Do NOT invent method names.',
        '// ============================================================',
    ];

    for (const ref of refs) {
        lines.push('//');
        lines.push(`// [${ref.className}]  — ${ref.namespace}::${ref.className}  (${ref.header})`);
        for (const method of ref.methods) {
            let line = `//   ${method.signature}`;
            const tag = `[${method.callRate}]`;
            if (method.paramRanges) {
                line += `  // ${method.paramRanges}  ${tag}`;
            } else {
                line += `  // ${tag}`;
            }
            lines.push(line);
            if (method.notes) {
                lines.push(`//     ^ ${method.notes}`);
            }
        }
    }

    lines.push('//');
    lines.push('// ============================================================');
    lines.push('');

    return lines.join('\n') + '\n';
}

/**
 * Variant that accepts node type IDs from a DVPE patch graph and resolves
 * class names via a provided lookup function.
 *
 * @param nodeTypes        Array of DVPE node type IDs (e.g. 'moog_ladder', 'adsr')
 * @param classNameLookup  Function mapping nodeType → C++ class name (from BlockRegistry)
 */
export function buildApiReferenceHeaderFromNodeTypes(
    nodeTypes: string[],
    classNameLookup: (nodeType: string) => string | undefined
): string {
    const classNames: string[] = [];
    for (const nodeType of nodeTypes) {
        const cls = classNameLookup(nodeType);
        if (cls) classNames.push(cls);
    }
    return buildApiReferenceHeader(classNames);
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

/**
 * Strips 'daisysp::' prefix, deduplicates, looks up API entries,
 * and returns them sorted alphabetically by class name.
 */
function collectUniqueRefs(rawClassNames: string[]): DaisyAPIRef[] {
    const seen = new Set<string>();
    const refs: DaisyAPIRef[] = [];

    for (const raw of rawClassNames) {
        const ref = lookupClass(raw);
        if (!ref) continue;                     // Not in index — skip
        if (seen.has(ref.className)) continue;  // Already added
        seen.add(ref.className);
        refs.push(ref);
    }

    // Alphabetical order so output is deterministic across runs
    return refs.sort((a, b) => a.className.localeCompare(b.className));
}
