// Generated by DVPE - Super Saw Pluck
// Refactored for Daisy Field
#include "daisy_field.h"
#include "daisysp.h"
#include <cstdio>

using namespace daisy;
using namespace daisysp;

// Hardware
DaisyField hw;

// DSP Modules
Oscillator osc_center;
Oscillator osc_right;
Oscillator osc_left;
Adsr       adsr_env;
MoogLadder filter;
ReverbSc   reverb;

// Signal Variables
float cv_midi_note_pitch  = 48.0f; // Default C3
float gate_midi_note_gate = 0.0f;

// Globals for MIDI
float g_midi_pitch    = 48.0f;
float g_midi_velocity = 0.0f;
bool  g_midi_gate     = false;

// Parameters
float p_detune = 0.0f;
float p_cutoff = 0.0f;
float p_decay  = 0.0f;
float p_reverb = 0.0f;

void HandleMidiMessage(MidiEvent m)
{
    switch(m.type)
    {
        case NoteOn:
        {
            NoteOnEvent p = m.AsNoteOn();
            if(p.velocity == 0.0f)
            {
                g_midi_gate = false;
            }
            else
            {
                g_midi_gate     = true;
                g_midi_pitch    = p.note;
                g_midi_velocity = p.velocity / 127.0f;
            }
        }
        break;
        case NoteOff:
        {
            g_midi_gate = false;
        }
        break;
        default: break;
    }
}

void AudioCallback(AudioHandle::InputBuffer  in,
                   AudioHandle::OutputBuffer out,
                   size_t                    size)
{
    hw.ProcessAnalogControls();
    hw.ProcessDigitalControls();

    // Map Controls
    // Knob 1: Detune
    p_detune = hw.GetKnobValue(0) * 0.04f;
    // Knob 2: Cutoff (Base)
    p_cutoff = 20.0f + (hw.GetKnobValue(1) * 5000.0f);
    // Knob 3: Decay
    p_decay = 0.1f + (hw.GetKnobValue(2) * 2.0f);
    adsr_env.SetTime(ADSR_SEG_DECAY, p_decay);
    // Knob 4: Reverb Mix
    p_reverb = hw.GetKnobValue(3);
    reverb.SetFeedback(0.8f + (p_reverb * 0.19f)); // 0.8 to 0.99

    // Logic: Use MIDI unless Keys are pressed
    if(hw.KeyboardState(0))
    {
        gate_midi_note_gate = 1.0f;
        cv_midi_note_pitch  = 48.0f; // C3
    }
    else if(hw.KeyboardState(1))
    {
        gate_midi_note_gate = 1.0f;
        cv_midi_note_pitch  = 50.0f; // D3
    }
    else if(g_midi_gate)
    {
        gate_midi_note_gate = 1.0f;
        cv_midi_note_pitch  = g_midi_pitch;
    }
    else
    {
        gate_midi_note_gate = 0.0f;
    }

    // Process Audio
    for(size_t i = 0; i < size; i++)
    {
        // Envelopes
        float env_out = adsr_env.Process(gate_midi_note_gate);

        // Oscillators (Super Saw)
        float freq_c = mtof(cv_midi_note_pitch);
        float freq_r = mtof(cv_midi_note_pitch
                            + (p_detune * 12.0f)); // Detune in semitones
        float freq_l = mtof(cv_midi_note_pitch - (p_detune * 12.0f));

        osc_center.SetFreq(freq_c);
        osc_right.SetFreq(freq_r);
        osc_left.SetFreq(freq_l);

        float sig_mix
            = (osc_center.Process() + osc_right.Process() + osc_left.Process())
              * 0.3f;

        // Filter
        filter.SetFreq(p_cutoff + (env_out * 5000.0f));
        float sig_filt = filter.Process(sig_mix);

        // Reverb
        float revL, revR;
        reverb.Process(sig_filt, sig_filt, &revL, &revR);

        // Output (Wet/Dry handled by just adding reverb for now, or use p_reverb)
        out[0][i] = sig_filt * (1.0f - p_reverb) + revL * p_reverb;
        out[1][i] = sig_filt * (1.0f - p_reverb) + revR * p_reverb;
    }
}

int main(void)
{
    hw.Init();
    float sr = hw.AudioSampleRate();

    // Init DSP
    osc_center.Init(sr);
    osc_center.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);
    osc_right.Init(sr);
    osc_right.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);
    osc_left.Init(sr);
    osc_left.SetWaveform(Oscillator::WAVE_POLYBLEP_SAW);

    adsr_env.Init(sr);
    adsr_env.SetTime(ADSR_SEG_ATTACK, 0.01f);
    adsr_env.SetTime(ADSR_SEG_RELEASE, 0.2f);

    filter.Init(sr);
    filter.SetRes(0.4f);

    reverb.Init(sr);
    reverb.SetLpFreq(10000.0f);

    hw.StartAdc();
    hw.midi.StartReceive();
    hw.StartAudio(AudioCallback);

    char buf[64];
    while(1)
    {
        hw.midi.Listen();
        while(hw.midi.HasEvents())
        {
            HandleMidiMessage(hw.midi.PopEvent());
        }

        hw.display.Fill(false);
        hw.display.SetCursor(0, 0);
        hw.display.WriteString("Super Saw Pluck", Font_7x10, true);

        // Show Parameters
        sprintf(buf, "NOTE: %d", (int)cv_midi_note_pitch);
        hw.display.SetCursor(0, 15);
        hw.display.WriteString(buf, Font_7x10, true);

        sprintf(buf, "Det: %d", (int)(p_detune * 1000));
        hw.display.SetCursor(0, 28);
        hw.display.WriteString(buf, Font_7x10, true);

        // Reverb instead of Decay for variety
        sprintf(buf, "Rev: %d", (int)(p_reverb * 100));
        hw.display.SetCursor(0, 41);
        hw.display.WriteString(buf, Font_7x10, true);

        hw.display.Update();
        System::Delay(16);
    }
}