name: Fix Style

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: DoozyX/clang-format-lint-action@v0.20
      with:
        source: '.'
        exclude: './DaisySP ./libDaisy ./DaisyTheory ./cube ./utils ./resources ./**/experimental'
        extensions: 'h,cpp'
        clangFormatVersion: 10
        inplace: True
    - uses: EndBug/add-and-commit@v10
      with:
        message: 'Automated: committing clang-format changes'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

