TARGET = Field_Template_Std_2
CPP_SOURCES = Field_Template_Std_2.cpp

LIBDAISY_DIR = ../../../libDaisy
DAISYSP_DIR  = ../../../DaisySP

SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
